//
// Decompiled by Procyon v0.5.30
//

package com.camtrack.config.passwordmanagement;

import java.math.BigDecimal;

public class Parameterconfigdefaultvalue {
	public static BigDecimal continiuousdrive_alarmhreshold;
	public static BigDecimal continiuousdrive_alertthreshold;
	public static BigDecimal continiuousdrive_minimumdistance;
	public static BigDecimal continiuousdrive_recordthreshold;
	public static BigDecimal continiuousdrive_requirerestime;
	public static BigDecimal continiuousdrive_thresholdlimit;
	public static BigDecimal dailydrive_alarmhreshold;
	public static BigDecimal dailydrive_alertthreshold;
	public static BigDecimal dailydrive_minimumdistance;
	public static BigDecimal dailydrive_recordthreshold;
	public static BigDecimal dailydrive_thresholdlimit;
	public static BigDecimal dailyrest_alarmhreshold;
	public static BigDecimal dailyrest_alertthreshold;
	public static BigDecimal dailyrest_minimumdistance;
	public static BigDecimal dailyrest_recordthreshold;
	public static BigDecimal dailyrest_thresholdlimit;
	public static BigDecimal dailywork_alarmhreshold;
	public static BigDecimal dailywork_alertthreshold;
	public static BigDecimal dailywork_minimumdistance;
	public static BigDecimal dailywork_recordthreshold;
	public static BigDecimal dailywork_thresholdlimit;
	public static BigDecimal fatigue_recordingdelayinput;
	public static BigDecimal fatigue_recordlimit;
	public static BigDecimal Harhsacc_alarmhreshold;
	public static BigDecimal Harhsacc_alertthreshold;
	public static BigDecimal Harhsacc_max_alarmdelayinput;
	public static BigDecimal Harhsacc_maxduration_alertdelayinput;
	public static BigDecimal Harhsacc_minduration_recordingdelayinput;
	public static BigDecimal Harhsacc_recordthreshold;
	public static BigDecimal Harsbraking_alarmhreshold;
	public static BigDecimal Harsbraking_alertthreshold;
	public static BigDecimal Harsbraking_max_alarmdelayinput;
	public static BigDecimal Harsbraking_maxduration_alertdelayinput;
	public static BigDecimal Harsbraking_minduration_recordingdelayinput;
	public static BigDecimal Harsbraking_recordthreshold;
	public static BigDecimal nightDriving_alarmhreshold;
	public static BigDecimal nightDriving_alertthreshold;
	public static Integer nightDriving_frommonth;
	public static String nightDriving_fromtime;
	public static BigDecimal nightDriving_minimumdistance;
	public static BigDecimal nightDriving_recordthreshold;
	public static Integer nightDriving_tommonth;
	public static String nightDriving_totime;
	public static BigDecimal noid_minimumdistance;
	public static BigDecimal phone_recordingdelayinput;
	public static BigDecimal phone_recordlimit;
	public static BigDecimal prev_dailydrive_thresholdlimit;
	public static BigDecimal prev_dailyrest_thresholdlimit;
	public static BigDecimal prev_weeklyRest_alarmhreshold;
	public static BigDecimal prev_weeklyRest_alertthreshold;
	public static BigDecimal prev_weeklyRest_minimumdistance;
	public static BigDecimal prev_weeklyRest_prevtrollingdays;
	public static BigDecimal prev_weeklyRest_recordthreshold;
	public static BigDecimal prev_weeklyRest_rollingdays;
	public static BigDecimal prev_weeklyRest_thresholdlimit;
	public static BigDecimal sealbelt_recordingdelayinput;
	public static BigDecimal sealbelt_recordlimit;
	public static BigDecimal speeding_alarmdelayinput;
	public static BigDecimal speeding_alarmhreshold;
	public static BigDecimal speeding_alarmthresholdperc;
	public static BigDecimal speeding_alertdelayinput;
	public static BigDecimal speeding_alertthreshold;
	public static BigDecimal speeding_alertthresholdperc;
	public static BigDecimal speeding_minimumdistance;
	public static BigDecimal speeding_recordingdelayinput;
	public static BigDecimal speeding_recordingthresholdperc;
	public static BigDecimal speeding_recordthreshold;
	public static BigDecimal speeding_thresholdlimit;
	public static BigDecimal weeklyDrive_alarmhreshold;
	public static BigDecimal weeklyDrive_alertthreshold;
	public static BigDecimal weeklyDrive_minimumdistance;
	public static BigDecimal weeklyDrive_recordthreshold;
	public static Integer weeklyDrive_rollingdays;
	public static BigDecimal weeklyDrive_thresholdlimit;
	public static BigDecimal weeklyRest_alarmhreshold;
	public static BigDecimal weeklyRest_alertthreshold;
	public static BigDecimal weeklyRest_minimumdistance;
	public static BigDecimal weeklyRest_recordthreshold;
	public static Integer weeklyRest_rollingdays;
	public static BigDecimal weeklyRest_thresholdlimit;

	static {
		Parameterconfigdefaultvalue.phone_recordlimit = new BigDecimal(15);
		Parameterconfigdefaultvalue.phone_recordingdelayinput = new BigDecimal(0.00168);
		Parameterconfigdefaultvalue.weeklyDrive_thresholdlimit = new BigDecimal(70);
		Parameterconfigdefaultvalue.weeklyDrive_rollingdays = 7;
		Parameterconfigdefaultvalue.weeklyDrive_recordthreshold = new BigDecimal(1);
		Parameterconfigdefaultvalue.weeklyDrive_alertthreshold = new BigDecimal(3);
		Parameterconfigdefaultvalue.weeklyDrive_alarmhreshold = new BigDecimal(5);
		Parameterconfigdefaultvalue.weeklyDrive_minimumdistance = new BigDecimal(0);
		Parameterconfigdefaultvalue.weeklyRest_thresholdlimit = new BigDecimal(70);
		Parameterconfigdefaultvalue.weeklyRest_rollingdays = 7;
		Parameterconfigdefaultvalue.weeklyRest_recordthreshold = new BigDecimal(1);
		Parameterconfigdefaultvalue.weeklyRest_alertthreshold = new BigDecimal(3);
		Parameterconfigdefaultvalue.weeklyRest_alarmhreshold = new BigDecimal(5);
		Parameterconfigdefaultvalue.weeklyRest_minimumdistance = new BigDecimal(0);
		Parameterconfigdefaultvalue.prev_weeklyRest_thresholdlimit = new BigDecimal(24);
		Parameterconfigdefaultvalue.prev_weeklyRest_prevtrollingdays = new BigDecimal(5);
		Parameterconfigdefaultvalue.prev_weeklyRest_rollingdays = new BigDecimal(7);
		Parameterconfigdefaultvalue.prev_weeklyRest_recordthreshold = new BigDecimal(1);
		Parameterconfigdefaultvalue.prev_weeklyRest_alertthreshold = new BigDecimal(3);
		Parameterconfigdefaultvalue.prev_weeklyRest_alarmhreshold = new BigDecimal(5);
		Parameterconfigdefaultvalue.prev_weeklyRest_minimumdistance = new BigDecimal(0.3);
		Parameterconfigdefaultvalue.sealbelt_recordlimit = new BigDecimal(15);
		Parameterconfigdefaultvalue.sealbelt_recordingdelayinput = new BigDecimal(0.00168);
		Parameterconfigdefaultvalue.noid_minimumdistance = new BigDecimal(0.5);
		Parameterconfigdefaultvalue.nightDriving_recordthreshold = new BigDecimal(0.25);
		Parameterconfigdefaultvalue.nightDriving_alertthreshold = new BigDecimal(0.5);
		Parameterconfigdefaultvalue.nightDriving_alarmhreshold = new BigDecimal(1);
		Parameterconfigdefaultvalue.nightDriving_minimumdistance = new BigDecimal(0);
		Parameterconfigdefaultvalue.nightDriving_frommonth = 1;
		Parameterconfigdefaultvalue.nightDriving_tommonth = 12;
		Parameterconfigdefaultvalue.nightDriving_fromtime = "20:00:00";
		Parameterconfigdefaultvalue.nightDriving_totime = "05:00:00";
		Parameterconfigdefaultvalue.Harsbraking_recordthreshold = new BigDecimal(6);
		Parameterconfigdefaultvalue.Harsbraking_alertthreshold = new BigDecimal(8);
		Parameterconfigdefaultvalue.Harsbraking_alarmhreshold = new BigDecimal(10);
		Parameterconfigdefaultvalue.Harsbraking_minduration_recordingdelayinput = new BigDecimal(2.8E-4);
		Parameterconfigdefaultvalue.Harsbraking_maxduration_alertdelayinput = new BigDecimal(8.4E-4);
		Parameterconfigdefaultvalue.Harsbraking_max_alarmdelayinput = new BigDecimal(8.4E-4);
		Parameterconfigdefaultvalue.Harhsacc_recordthreshold = new BigDecimal(4);
		Parameterconfigdefaultvalue.Harhsacc_alertthreshold = new BigDecimal(6);
		Parameterconfigdefaultvalue.Harhsacc_alarmhreshold = new BigDecimal(8);
		Parameterconfigdefaultvalue.Harhsacc_minduration_recordingdelayinput = new BigDecimal(2.8E-4);
		Parameterconfigdefaultvalue.Harhsacc_maxduration_alertdelayinput = new BigDecimal(8.4E-4);
		Parameterconfigdefaultvalue.Harhsacc_max_alarmdelayinput = new BigDecimal(8.4E-4);
		Parameterconfigdefaultvalue.fatigue_recordlimit = new BigDecimal(15);
		Parameterconfigdefaultvalue.fatigue_recordingdelayinput = new BigDecimal(0.00168);
		Parameterconfigdefaultvalue.continiuousdrive_thresholdlimit = new BigDecimal(2);
		Parameterconfigdefaultvalue.continiuousdrive_recordthreshold = new BigDecimal(0.16667);
		Parameterconfigdefaultvalue.continiuousdrive_alertthreshold = new BigDecimal(0.33333);
		Parameterconfigdefaultvalue.continiuousdrive_alarmhreshold = new BigDecimal(0.5);
		Parameterconfigdefaultvalue.continiuousdrive_requirerestime = new BigDecimal(0.16667);
		Parameterconfigdefaultvalue.continiuousdrive_minimumdistance = new BigDecimal(0.3);
		Parameterconfigdefaultvalue.dailyrest_thresholdlimit = new BigDecimal(9);
		Parameterconfigdefaultvalue.prev_dailyrest_thresholdlimit = new BigDecimal(7);
		Parameterconfigdefaultvalue.dailyrest_recordthreshold = new BigDecimal(0.25);
		Parameterconfigdefaultvalue.dailyrest_alertthreshold = new BigDecimal(0.5);
		Parameterconfigdefaultvalue.dailyrest_alarmhreshold = new BigDecimal(1);
		Parameterconfigdefaultvalue.dailyrest_minimumdistance = new BigDecimal(0.3);
		Parameterconfigdefaultvalue.dailywork_thresholdlimit = new BigDecimal(9);
		Parameterconfigdefaultvalue.dailywork_recordthreshold = new BigDecimal(0.25);
		Parameterconfigdefaultvalue.dailywork_alertthreshold = new BigDecimal(0.5);
		Parameterconfigdefaultvalue.dailywork_alarmhreshold = new BigDecimal(1);
		Parameterconfigdefaultvalue.dailywork_minimumdistance = new BigDecimal(0.3);
		Parameterconfigdefaultvalue.dailydrive_thresholdlimit = new BigDecimal(10);
		Parameterconfigdefaultvalue.prev_dailydrive_thresholdlimit = new BigDecimal(9);
		Parameterconfigdefaultvalue.dailydrive_recordthreshold = new BigDecimal(0.25);
		Parameterconfigdefaultvalue.dailydrive_alertthreshold = new BigDecimal(0.5);
		Parameterconfigdefaultvalue.dailydrive_alarmhreshold = new BigDecimal(1);
		Parameterconfigdefaultvalue.dailydrive_minimumdistance = new BigDecimal(0.3);
		Parameterconfigdefaultvalue.speeding_thresholdlimit = new BigDecimal(0);
		Parameterconfigdefaultvalue.speeding_recordthreshold = new BigDecimal(3);
		Parameterconfigdefaultvalue.speeding_alertthreshold = new BigDecimal(6);
		Parameterconfigdefaultvalue.speeding_alarmhreshold = new BigDecimal(12);
		Parameterconfigdefaultvalue.speeding_recordingdelayinput = new BigDecimal(0.00833);
		Parameterconfigdefaultvalue.speeding_alertdelayinput = new BigDecimal(0.00556);
		Parameterconfigdefaultvalue.speeding_alarmdelayinput = new BigDecimal(0.00278);
		Parameterconfigdefaultvalue.speeding_recordingthresholdperc = new BigDecimal(0.05);
		Parameterconfigdefaultvalue.speeding_alertthresholdperc = new BigDecimal(0.1);
		Parameterconfigdefaultvalue.speeding_alarmthresholdperc = new BigDecimal(0.2);
		Parameterconfigdefaultvalue.speeding_minimumdistance = new BigDecimal(0.3);
	}
}
